### ISSUE TITLE
Can I force IntelliJ to ignore certain Haxe 4 "syntax errors"?

### ISSUE THREAD

**Issue by Kyliathy** [HaxeFoundation/intellij-haxe#914]
Hey :). The BuilderClass below breaks IntelliJ's code completion features for that class because it fails to parse it. Unfortunately for me, it's one of the main classes in my project and missing code completion features for it is kind of annoying. For now, I'll work around it by declaring some fields in a subclass.

I'm pasting a sample that compiles with Haxe 4.

`class Main
{
	static function main ()
	{
		var triggerClass: TriggerClass = new TriggerClass("abc");
		trace(triggerClass.toStringDump());
	}
}

enum SomeEnum
{
	Member1;
	Member2;
}

class WantToBeBuilt
{
	public var desc: String;
	public var someEnum: SomeEnum;

	public function new (desc: String, someEnum: SomeEnum)
	{
		this.desc = desc;
		this.someEnum = someEnum;
	}

	public function toStringDump(): String
	{
		return desc + " " + someEnum.getName();
	}
}

@:generic
class BuilderClass<T:haxe.Constraints.Constructible<String->SomeEnum->Void> & {function toStringDump (): String;}>
{
	public var name: String;
	public var instance: T;

	public function new (name: String)
	{
		this.name = name;
		//Error:(54, 3) Constraint check failure for
		//build.T haxe.Constructible<(String, SomeEnum) -> Void> should be { toStringDump : Void -> String }
		build(name, SomeEnum.Member1);
		//build<T>(name, SomeEnum.Member1); //Error:(54, 26) Unexpected . (no other errors)
	}

	public function build
	(desc: String, someEnum: SomeEnum): Void
	{
		instance = new T(desc, someEnum); //Error:(61, 3) build.T should be BuilderClass.T
	}

	public function toString(): String
	{
		return "BuilderClass name: " + name;
	}
}

class TriggerClass extends BuilderClass<WantToBeBuilt>
{
	public function new (name: String)
	{
		super(name);
	}

	public function toStringDump(): String
	{
		return super.toString();
	}
}
`

**Comment by EricBishton** [comment]
Hi @Kyliathy 

The example above doesn't compile with 4.0 either (using 20190216112239_a5323ba build).
http://try-haxe.mrcdk.com/#e3858

Test.hx:66: characters 28-40 : Invalid number of type parameters for BuilderClass

**Comment by Kyliathy** [comment]
Hey Eric :) and thank you for answering during the weekend. I guess we're all quite devoted eh? :D. 

Sorry for the wrong sample. I guess I must have made a copy paste error. Here's one that I triple-checked that it compiles via IJ / Haxe 4 RC1.

http://try-haxe.mrcdk.com/#B3010

**Comment by EricBishton** [comment]
So, this one has an easy workaround: Use the older style, but equivalent `,` for type lists and create a typedef for the constant structure, rather than using one defined in-line.  (It has the advantage of being more readable, too.)

```haxe
typedef Stringable = {function toStringDump():String;};
@:generic
class BuilderClass<T:haxe.Constraints.Constructible<String -> SomeEnum -> Void>, Stringable> {
  ...
}
```
As far as turning on/off language features, that is something else I am working on.  They will change based upon the Haxe SDK you are using in your project.  So, you (will) simply define multiple SDKs and switch between them at the project level.

Whether to limit the syntax based upon a compiler level regardless of the SDK in use is something I hadn't considered and I'm frankly not sure whether there is a large-enough demand.  For sure, there are other things that I should spend my time on in the near future.

So, the short answer to your original question "Can I force IntelliJ to ignore certain Haxe 4 "syntax errors?" is, "No."  :)

**Comment by EricBishton** [comment]
As far as the underlying issue getting implemented, that is Issue #845.

**Comment by Gama11** [comment]
>So, this one has an easy workaround: Use the older style [...]

Note that the older style doesn't work in Haxe 4 anymore - I think this might be the only breaking syntax change in in Haxe 4. That's why the [example in the manual](https://haxe.org/manual/type-system-type-parameter-constraints.html) uses a Haxe version check.

(also, the old still requires parens around the types)

**Comment by EricBishton** [comment]
Ah.  Mea culpa.  That's what I get for not re-checking with the older compiler after I fixed the example in IDEA.  :/

**Comment by Kyliathy** [comment]
Ok, so for now I can't do this in Haxe 4. I'm fine with my ugly subclass workaround for now.

**Comment by EricBishton** [comment]
I've edited my answer above.  There is a better solution than your subclass workaround.

**Comment by Kyliathy** [comment]
Unfortunately it still doesn't work. I'm posting a picture, this time with objects from my real code, not from the sample I posted earlier. The code compiles and runs fine.

![hover](https://user-images.githubusercontent.com/20860173/52904418-5e169980-322c-11e9-9ddc-4cc5507633b3.png)

![nope](https://user-images.githubusercontent.com/20860173/52904419-61aa2080-322c-11e9-8cc6-c7c7417a4e30.png)

**Comment by Kyliathy** [comment]
Oh, and just so you know, the example below works just fine in IntelliJ! :)

class CollectionParentBase<T, U:{function toStringDump():String;}> extends CollectionBase implements CollectionParentI<T, U>

**Comment by EricBishton** [comment]
Does the `#if (haxe_ver >= 4)...#else...#end` pattern (see the edited comment above) not fix things for you?

**Comment by Kyliathy** [comment]
Just to make sure: this still doesn't work, so I think this shouldn't be closed :)

**Comment by EricBishton** [comment]
If you are referring to the fact that we don't parse the & in that position, then this is a duplicate of #845, which remains open.  If you are referring to the `#if (haxe_ver>=4) ... #else ... #end` workaround not working, then I'll need to look at your module settings and code snippet so we can get that working for you.

**Comment by Kyliathy** [comment]
Yeap, it's about 845, which actually shows up as closed.

I got used to the workaround thingy. I'm fine with that file not parsing for now. Minor nuisance. Hope you reopen and get 845 working though :D

**Comment by Gama11** [comment]
Not sure what you're seeing, but that issue is not closed:

![](https://i.imgur.com/CzcSfog.png)

**Comment by Kyliathy** [comment]
LOL. GitHub UX and my brain didn't get along well. I confused it with #914 which is listed as closed. That shows as the last thing in the issue history. Since I haven't been hanging around GitHub that much, my brain didn't parse the UX properly :D
